# Description:
#
# This function caluclates 4 different values of the parameter "beta" for not selection, weak selection,
# medium selection and stong selection following the "Stress Model". 
#
# Usage:
#
# CalculateBetas(chain.p.ref, fmax, R0, heme = TRUE/FALSE, data.dir, out.dir,
# betas.fname.id, TOLERANCE)
#
#  Args:
#    - chain.p.ref: the chain of p.ref in the pdb file obtained from Homstrad.
#    - fmax: It is the maximun value for the forces that model the mutations.
#    - R0: the cut-off for the ANM ("Anisotropic Network Model") that represents the proteins.
#    - heme: argument for "globins". It can be "TRUE" or "FALSE". If it is "TRUE", the program considers the heme group.
#    - data.dir: directory of the data. It must contain the pdb file obtained from Homstrad ("data.dir/family_coordinates.csv").
#    - out.dir: output directory. It must contain the output generated by the function AnalyzeFamily().
#    - betas.fname.id: ID for output filenames.
#    - TOLERANCE: 0 tolerance.
#
#  Required libraries:
#    {Bio3d}
#
#  Required function:
#    ReadCA()
#    ReadHeme()
#    CalculateENMK()
#    CalculateKij()

CalculateBetas <- function(chain.p.ref,
                          fmax, 
                          R0,
                          heme,
                          data.dir,
                          out.dir,
                          betas.fname.id,
                          TOLERANCE) {
  
  ### READ EXPERIMENTAL DATA ###
  
  # Filenames.
  pdbs.fname <- file.path(data.dir, paste(family, "_coordinates.pdb", sep = "")) 
  
  # Read PDB of p.ref.
  pdb = ReadCA(pdbs.fname, chain.p.ref)
  r.p.ref = pdb$xyz.calpha
  n.aa = pdb$n.sites
  
  # Get heme coordinates, add them to CA´s coordinates and calculate the new number of sites.
  if (heme == "TRUE") {
    r.heme = ReadHeme(pdbs.fname, chain.p.ref)
    r.p.ref = cbind(r.p.ref, r.heme)
    n.sites = ncol(r.p.ref)
  } else {
    n.sites = n.aa
  }
  
  ### CALCULATE ENM OF THE REFERENCE PROTEIN ###
  
  # Calculate K of p.ref.
  ENMK.p.ref = CalculateENMK(r.p.ref, CalculateKij, R0, TOLERANCE) 
  
  ### CALCULATE PARAMETERS FOR THE SELECTION OF MUTANTS FOLLOWING THE "STRESS MODEL" ###
  
  # Calculate "mean.CN".
  mean.CN = mean(colSums(ENMK.p.ref$kij)) 
  
  # Calculate "f2" (see the function CalculateForce()).
  f2 = mean((fmax * runif(1e6, -1, 1)) ^ 2)
  
  # Caculate betas for differente selection regimes.
  beta.0.2 = - log(0.2) / (f2 * mean.CN) # Strong selection.
  beta.0.5 = - log(0.5) / (f2 * mean.CN) # Medium.
  beta.0.8 = - log(0.8) / (f2 * mean.CN) # Weak selection.
  beta.1 = - log(1) / (f2 * mean.CN) # No selection.
  
  # Build a list with betas.
  all.betas = list("strong.sel" = beta.0.2, "medium.sel" = beta.0.5, "weak.sel" = beta.0.8, "no.sel" = beta.1) 
  
  # Create a file to save the data.
  write.csv(all.betas, file = file.path(out.dir, paste(betas.fname.id, "_out_all.betas.csv", sep = "")), row.names = FALSE)
}
