---
title: "MSDi for all families together"
author: "Maria Laura Marcos"
output: html_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE)
```

```{r}

# Directories.
out.dir <- "OUT"

# Create matrixes.
nsF.theo.MSDi = c()
nsT.theo.MSDi = c()
nsF.theo.MSDi.s = c()
nsT.theo.MSDi.s = c()

exp.MSDi = c()
exp.MSDi.s = c()

# Read input.
input.fname <- file.path("input_MainMultipleReport.csv")
input <- read.csv(input.fname)

# Print the input in the html file.
print(input)

# Start a loop to read data for each family.
for (a in (1:nrow(input))) { 
  family <- as.character(input$family)[a]
  mut.model = input$mut.model[a]
  R0 = input$R0[a]
  K.analysis = input$K.analysis[a]
  
  #Read experimental data.
  analysis.fname.id <- paste(family, "_mut.model_", mut.model, "_naturalSelection_", "FALSE", "_R0_", R0, "_core_", "FALSE", "_K.analysis_", K.analysis, sep = "")
  
  m.cF.exp.dr.squarei = read.csv(file.path(out.dir, paste(analysis.fname.id, "_out_m.exp.dr.squarei.csv", sep = "")))
  m.cF.exp.smooth.dr.squarei = read.csv(file.path(out.dir, paste(analysis.fname.id, "_out_m.exp.smooth.dr.squarei.csv", sep = "")))
  
  
  cF.exp.MSDi = colMeans(m.cF.exp.dr.squarei, na.rm = T )
  cF.exp.MSDi.s = colMeans(m.cF.exp.smooth.dr.squarei, na.rm = T )
  
  #Read theoretical data#
  
  # natural selection (ns) = F.
  m.nsF.cF.theo.dr.squarei = read.csv(file.path(out.dir, paste(analysis.fname.id, "_out_m.theo.dr.squarei.csv", sep = "")))
  m.nsF.cF.theo.smooth.dr.squarei = read.csv(file.path(out.dir, paste(analysis.fname.id, "_out_m.theo.smooth.dr.squarei.csv", sep = "")))
  
  nsF.cF.theo.MSDi = colMeans(m.nsF.cF.theo.dr.squarei, na.rm = T)
  nsF.cF.theo.MSDi.s = colMeans(m.nsF.cF.theo.smooth.dr.squarei, na.rm = T)
  
  # natural selection (ns) = T.
  analysis.fname.id <- paste(family, "_mut.model_", mut.model, "_naturalSelection_", "TRUE", "_R0_", R0, "_core_", "FALSE", "_K.analysis_", K.analysis, sep = "")
  
  m.nsT.cF.theo.dr.squarei = read.csv(file.path(out.dir, paste(analysis.fname.id, "_out_m.theo.dr.squarei.csv", sep = "")))
  m.nsT.cF.theo.smooth.dr.squarei = read.csv(file.path(out.dir, paste(analysis.fname.id, "_out_m.theo.smooth.dr.squarei.csv", sep = "")))
  
  nsT.cF.theo.MSDi = colMeans(m.nsT.cF.theo.dr.squarei, na.rm = T)
  nsT.cF.theo.MSDi.s = colMeans(m.nsT.cF.theo.smooth.dr.squarei, na.rm = T)
  
  ## Fit theoretical data with experimental data.
  fit.nsF.cF = lm(cF.exp.MSDi ~ nsF.cF.theo.MSDi)
  fit.nsF.cF.MSDi = fitted.values(fit.nsF.cF)
  
  fit.nsT.cF = lm(cF.exp.MSDi ~ nsT.cF.theo.MSDi)
  fit.nsT.cF.MSDi = fitted.values(fit.nsT.cF)
  
  fit.nsF.cF.s = lm(cF.exp.MSDi.s ~ nsF.cF.theo.MSDi.s)
  fit.nsF.cF.MSDi.s = fitted.values(fit.nsF.cF.s)
  
  fit.nsT.cF.s = lm(cF.exp.MSDi.s ~ nsT.cF.theo.MSDi.s)
  fit.nsT.cF.MSDi.s = fitted.values(fit.nsT.cF.s)
  
  # Concatenate information.
  nsF.theo.MSDi = c(nsF.theo.MSDi, fit.nsF.cF.MSDi)
  nsT.theo.MSDi = c(nsT.theo.MSDi, fit.nsT.cF.MSDi)
  nsF.theo.MSDi.s = c(nsF.theo.MSDi.s, fit.nsF.cF.MSDi.s)
  nsT.theo.MSDi.s = c(nsT.theo.MSDi.s, fit.nsT.cF.MSDi.s)
  
  cF.exp.MSDi = cF.exp.MSDi[!is.na(cF.exp.MSDi)]
  cF.exp.MSDi.s = cF.exp.MSDi.s[!is.na(cF.exp.MSDi.s)]
  
  exp.MSDi = c(exp.MSDi, cF.exp.MSDi)
  exp.MSDi.s = c(exp.MSDi.s, cF.exp.MSDi.s)
}

# Caluclate measures.
R2.nsF.cF = cor(nsF.theo.MSDi, exp.MSDi) ^ 2 
R2.nsT.cF = cor(nsT.theo.MSDi, exp.MSDi) ^ 2 

R2.nsF.cF.s = cor(nsF.theo.MSDi.s, exp.MSDi.s) ^ 2
R2.nsT.cF.s = cor(nsT.theo.MSDi.s, exp.MSDi.s) ^ 2  

MSE.nsF.cF = mean((nsF.theo.MSDi - exp.MSDi) ^ 2)
MSE.nsT.cF = mean((nsT.theo.MSDi - exp.MSDi) ^ 2)

MSE.nsF.cF.s = mean((nsF.theo.MSDi.s - exp.MSDi.s) ^ 2)
MSE.nsT.cF.s = mean((nsT.theo.MSDi.s - exp.MSDi.s) ^ 2)

```

```{r, include = F}
layout(matrix(1:3, 3, 1, byrow = F)) 

plot(nsF.theo.MSDi, type = "l", xlab = "sitio", ylab = "Theoretical")
plot(exp.MSDi, type = "l", col = "red", ylab = "Experimental")
plot(nsF.theo.MSDi, type = "l", ylab = "both")
points(exp.MSDi, col = "red", type = "l")
legend("topleft", paste("R^2", round(R2.nsF.cF, digits = 2)), bty = "n", text.col = "red")

```

```{r, include = F}
layout(matrix(1:3, 3, 1, byrow = F)) 
plot(nsT.theo.MSDi, type="l", xlab = "sitio", ylab = "Theoretical")
plot(exp.MSDi, type="l", col ="red", ylab = "Experimental")
plot(nsT.theo.MSDi, type="l", ylab = "both")
points(exp.MSDi, col = "red", type="l")
legend("topleft", paste("R^2", round(R2.nsT.cF, digits = 2)), bty = "n", text.col = "red")
```
All families fitted smooth normalized MSD profiles 

Without natural selection (ns = F)

```{r}
plot(nsF.theo.MSDi.s, type = "l", xlab = "sitio", ylab = "Theoretical ns = F", ylim = c(0, 0.14))
```

```{r}
plot(exp.MSDi.s, type = "l", col = "red", ylab = "Experimental", ylim = c(0, 0.14))
```

```{r}
plot(nsF.theo.MSDi.s, type = "l", ylab = "both", ylim = c(0, 0.14))
points(exp.MSDi.s, col = "red", type = "l")
legend("topleft", paste("R^2", round(R2.nsF.cF.s, digits = 2), " ", "MSE", signif(MSE.nsF.cF.s, digits = 4)), bty = "n", text.col = "red")
```

With natural selection (ns = T)

```{r}
plot(nsT.theo.MSDi.s, type="l", xlab = "sitio", ylab = "Theoretical ns = T", ylim = c(0, 0.14))
```

```{r}
plot(exp.MSDi.s, type = "l", col = "red", ylab = "Experimental", ylim = c(0, 0.14))
```

```{r}
plot(nsT.theo.MSDi.s, type = "l", ylab = "both", ylim = c(0, 0.14))
points(exp.MSDi.s, col = "red", type = "l")
legend("topleft", paste("R^2", round(R2.nsT.cF.s, digits = 2), " ", "MSE", signif(MSE.nsT.cF.s, digits = 2)), bty = "n", text.col = "red")
```

