---
title: "Structural Divergence Analysis"
author: "Maria Laura Marcos, Julian Echave"
output: html_document
---


# Introduction


```{r setup, include = FALSE}
# set chunk options
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load-packages}
# load packages
library(ggplot2)
library(reshape2)
library(plyr)
library(quantreg)
library(bio3d)

# load functions
source("FUNCTIONS/ReadCA.R") 
source("FUNCTIONS/CalculateSideChainCM.R")
source(file.path(data.dir, "multiplot.R"))
source(file.path(data.dir, "my-functions.R"))
```

```{r set-file-names}
# set input filenames

## CM
data.dir <- paste("OUT/out_subset_CM_ANM", sep = "")
R0 = R0.CM
  
## data
reference.fname = file.path(data.dir, paste(family, "_ref.txt", sep = ""))
protein_list.fname = file.path(data.dir, paste(family, "_list.txt", sep = ""))

## profiles to compare
dri2.exp.fname = file.path(data.dir, paste(family, "_R0_", R0, "_beta_no.sel_K.analysis_Keff_out_m.exp.norm.dr.squarei.csv", sep = ""))
dri2.medium.fname = file.path(data.dir, paste(family, "_R0_", R0, "_beta_medium.sel_K.analysis_Keff_out_m.theo.norm.dr.squarei.csv", sep = ""))
dri2.mut.fname = file.path(data.dir,paste(family, "_R0_", R0, "_beta_no.sel_K.analysis_Keff_out_m.theo.norm.dr.squarei.csv", sep = ""))

## consurf
score.fname = file.path(data.dir, paste(p.ref, "_consurf.csv", sep = ""))
sim.data.mut.fname = file.path(data.dir, paste(family, "_R0_", R0, "_beta_no.sel_out_df.data.csv", sep = ""))
sim.data.medium.sel.fname = file.path(data.dir, paste(family, "_R0_", R0, "_beta_medium.sel_out_df.data.csv", sep = ""))
```

```{r set-reference-protein}
# which is the reference protein?
reference = as.character(read.table(reference.fname, header = F)[1, 1])
if (reference != p.ref) {
  print("Warning: different references")
}
```


In this case we studied the `r family` family. 
We used as reference for the ENM the protein with pdb code `r reference`. 
We simulated `r n.mut.p` mutants of this reference for each protein of the family.
The `r family` family is of the type `r type` and consists of the following proteins:


```{r set-experimental-protein-names}
# experimental protein names
protein.exp = read.table(protein_list.fname, header = F, stringsAsFactors = F)[, 1]
protein.exp = protein.exp[protein.exp != reference]
print(protein.exp)
```

```{r set-site-info, include = FALSE}

# read reference pdb and calculate resno, AA, and CN
reference.pdb.fname = file.path(data.dir,paste(reference, ".pdb", sep = ""))
ref.pdb = read.pdb(reference.pdb.fname)
inds = atom.select(ref.pdb, elety = "CA")
ref.pdb.ca = ref.pdb$atom[inds$atom, ]
n.sites = length(ref.pdb.ca$resid)
AA = ref.pdb.ca$resid
resno = seq(1:n.sites)
pdb.info = data.frame(resno, AA)
names(pdb.info) = c("resno", "AA")
print(n.sites)

site.info = pdb.info

### CA ###

# calculate CN
R0 = -0.1
cmap.ca.1 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.neg.0.1.CA = rep(0, n.sites)

R0 = 2.5
cmap.ca.R0.2.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.2.5.CA = rep(0, n.sites)

R0 = 7.5
cmap.ca.R0.7.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.7.5.CA = rowSums(cmap.ca.R0.7.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 12.5
cmap.ca.R0.12.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.12.5.CA = rowSums(cmap.ca.R0.12.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 17.5
cmap.ca.R0.17.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.17.5.CA = rowSums(cmap.ca.R0.17.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 22.5
cmap.ca.R0.22.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.22.5.CA = rowSums(cmap.ca.R0.22.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 27.5
cmap.ca.R0.27.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.27.5.CA = rowSums(cmap.ca.R0.27.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 32.5
cmap.ca.R0.32.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.32.5.CA = rowSums(cmap.ca.R0.32.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 37.5
cmap.ca.R0.37.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.37.5.CA = rowSums(cmap.ca.R0.37.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 42.5
cmap.ca.R0.42.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.42.5.CA = rowSums(cmap.ca.R0.42.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 47.5
cmap.ca.R0.47.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.47.5.CA = rowSums(cmap.ca.R0.47.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

R0 = 52.5
cmap.ca.R0.52.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.52.5.CA = rowSums(cmap.ca.R0.52.5, na.rm = T) - 1 # diag(cmap.ca) returned by cmap is 1!

# calculate WCN
r.p.ref = matrix(ref.pdb$xyz[inds$xyz], nrow = 3)
dist.r.p.ref = dist.xyz(t(r.p.ref))
WCN.CA = c()
for (i in (1:ncol(r.p.ref))) {
  WCN.CA[i] = sum(1/dist.r.p.ref[i, -i]^2)
}

### CM ###

# Read PDB of p.ref
pdb.ca = ReadCA(reference.pdb.fname, chain.p.ref)
r.ca.p.ref = pdb.ca$xyz.calpha
r.CM.p.ref = CalculateSideChainCM(reference.pdb.fname, chain.p.ref)
r.p.ref = cbind(r.CM.p.ref, r.ca.p.ref)
  
# calculate CN
R0 = -0.1
cmap.CM.1 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.neg.0.1.CM = rep(0, n.sites)

R0 = 2.5
cmap.CM.R0.2.5 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.2.5.CM = rep(0, n.sites)

R0 = 7.5
cmap.CM.R0.7.5 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.7.5.CM = (rowSums(cmap.CM.R0.7.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 12.5
cmap.CM.12.5 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.12.5.CM = (rowSums(cmap.CM.12.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 17.5
cmap.CM.R0.17.5 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.17.5.CM = (rowSums(cmap.CM.R0.17.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 22.5
cmap.CM.R0.22.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.22.5.CM = (rowSums(cmap.CM.R0.22.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 27.5
cmap.CM.R0.27.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.27.5.CM = (rowSums(cmap.CM.R0.27.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 32.5
cmap.CM.R0.32.5 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.32.5.CM = (rowSums(cmap.CM.R0.32.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 37.5
cmap.CM.R0.37.5 = cmap(as.vector(r.p.ref), dcut = R0, scut = 0, mask.lower = F)
CN.R0.37.5.CM = (rowSums(cmap.CM.R0.37.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 42.5
cmap.CM.R0.42.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.42.5.CM = (rowSums(cmap.CM.R0.42.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 47.5
cmap.CM.R0.47.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.47.5.CM = (rowSums(cmap.CM.R0.47.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

R0 = 52.5
cmap.CM.R0.52.5 = cmap(ref.pdb$xyz[inds$xyz], dcut = R0, scut = 0, mask.lower = F)
CN.R0.52.5.CM = (rowSums(cmap.CM.R0.52.5, na.rm = T) - 2)[1:ncol(r.CM.p.ref)]

# calculate WCN
dist.r.CM.p.ref = dist.xyz(t(r.p.ref))
WCN.CM = c()
for (i in (1:ncol(r.CM.p.ref))) {
  WCN.CM[i] = sum(1/(dist.r.CM.p.ref[i, -c(i, (i + ncol(r.CM.p.ref)))]^2))
}

```

```{r read-data}
# read data
## exp
dri2.exp = read.csv(dri2.exp.fname, header = T)
site = site.info$site
rownames(dri2.exp) = paste("exp", rownames(dri2.exp), sep = "")

## mut
dri2.mut = read.csv(dri2.mut.fname, header = T)
rownames(dri2.mut) = paste("mut", rownames(dri2.mut), sep = "")

## medium
dri2.medium = read.csv(dri2.medium.fname, header = T)
rownames(dri2.medium) = paste("medium", rownames(dri2.medium), sep = "")
```


```{r prepare-site-data}
# prepare the data
## exp
tdri2.exp = as.data.frame(t(as.matrix(dri2.exp)))
tdri2.exp = cbind(site.info, tdri2.exp)
siteComparison.exp = melt(tdri2.exp, id.vars = names(site.info), variable.name = "protein", value.name = "dri2")

## mut
tdri2.mut = as.data.frame(t(as.matrix(dri2.mut)))
tdri2.mut = cbind(site.info, tdri2.mut)
siteComparison.mut = melt(tdri2.mut, id.vars = names(site.info), variable.name = "protein", value.name = "dri2")

## medium
tdri2.medium = as.data.frame(t(as.matrix(dri2.medium)))
tdri2.medium = cbind(site.info, tdri2.medium)
siteComparison.medium = melt(tdri2.medium, id.vars = names(site.info), variable.name = "protein", value.name = "dri2")

# bluild the data.frame
siteComparison.all.datasets = rbind(data.frame("dataset" = "exp", siteComparison.exp),
                                    data.frame("dataset" = "mut", siteComparison.mut),
                                    data.frame("dataset" = "medium", siteComparison.medium))

siteComparison.all.datasets = ddply(siteComparison.all.datasets, c("dataset", "protein"), mutate,
                     "n.SD" = dri2/mean(dri2, na.rm = T),
                     "z.SD" = vscale(dri2),
                      "RSD" = sqrt(dri2),
                    "n.RSD" = RSD/mean(RSD, na.rm = T),
                    "z.RSD" = vscale(RSD))
```


```{r mean-se-z.RSD-vs-site}
# comparison of z.RSD profiles with functional sites
## prepare dat
dat = siteComparison.all.datasets
dat$dataset = revalue(dat$dataset, c("medium" = "selection"))
dat$dataset = revalue(dat$dataset, c("mut" = "no-selection"))

## dat with means and standard errors
d = ddply(dat,c("dataset", "resno"), function(x) {
                mean.z.RSD = mean(x$z.RSD, na.rm = T)
                ndata = sum(!is.na(x$z.RSD))
                se.z.RSD = sd(x$z.RSD, na.rm = T) / sqrt(ndata)
                data.frame(mean.z.RSD, ndata, se.z.RSD)
})


# calculate correlations berween profiles
d.exp = subset(d, dataset == "exp")
d.mut = subset(d, dataset == "no-selection")
d.medium = subset(d, dataset == "selection")
```
### Sequence - structure comparison

```{r structure-CN-WCN-CA-comparison}

# compare profiles

CA.cor.p = c()
CA.cor.s = c()

## plot
par(pty = "s")

plot(x = d.exp$mean.z.RSD, y = CN.R0.neg.0.1.CA, xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.neg.0.1.CA)
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.neg.0.1.CA, method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

######## 

plot(x = d.exp$mean.z.RSD, y = CN.R0.2.5.CA, xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.2.5.CA)
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.2.5.CA, method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.7.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.7.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.7.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.12.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.12.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.12.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.17.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.17.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.17.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.22.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.22.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.22.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.27.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.27.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.27.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.32.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.32.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.32.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.37.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.37.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.37.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.42.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.42.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.42.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.47.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.47.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.47.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.52.5.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.52.5.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.52.5.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

# WCN
plot(x = d.exp$mean.z.RSD, y = log(WCN.CA), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(WCN.CA))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(WCN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (WCN)")
CA.cor.p = c(CA.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(WCN.CA), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(WCN)"),
                             "R" = r.exp.mean.z.RSD.CN)

knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (WCN)")
CA.cor.s = c(CA.cor.s, r.exp.mean.z.RSD.CN)

```



```{r structure-CN-WCN-CM-comparison}

# compare profiles

CM.cor.p = c()
CM.cor.s = c()

## plot
par(pty = "s")

plot(x = d.exp$mean.z.RSD, y = CN.R0.neg.0.1.CM, xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.neg.0.1.CM)
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.neg.0.1.CM, method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

######## 

plot(x = d.exp$mean.z.RSD, y = CN.R0.2.5.CM, xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.2.5.CM)
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, CN.R0.2.5.CM, method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs CN"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.7.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.7.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.7.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.12.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.12.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.12.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.17.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.17.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.17.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.22.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.22.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.22.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.27.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.27.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.27.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.32.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.32.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.32.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#######
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.37.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.37.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.37.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.42.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.42.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.42.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.47.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.47.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.47.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

#####
plot(x = d.exp$mean.z.RSD, y = log(CN.R0.52.5.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.52.5.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(CN.R0.52.5.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(CN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (CN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

# WCN
plot(x = d.exp$mean.z.RSD, y = log(WCN.CM), xlab = "<zRSDi> experimental")

## calculate correlations
r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(WCN.CM))
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(WCN)"),
                             "R" = r.exp.mean.z.RSD.CN)
knitr::kable(cor.df, digits = 2, caption = "Pearson Correlation structure (<z.RSD>) - sequence (WCN)")
CM.cor.p = c(CM.cor.p, r.exp.mean.z.RSD.CN)

r.exp.mean.z.RSD.CN = cor(d.exp$mean.z.RSD, log(WCN.CM), method = "spearman")
cor.df = data.frame("comparison" = c("<z.RSD> experimental vs log(WCN)"),
                             "R" = r.exp.mean.z.RSD.CN)

knitr::kable(cor.df, digits = 2, caption = "Spearman Correlation structure (<z.RSD>) - sequence (WCN)")
CM.cor.s = c(CM.cor.s, r.exp.mean.z.RSD.CN)

```


### All correlations

```{r correlations}
# build a data frame
cor = data.frame("CA pearson" = CA.cor.p,
                 "CM pearson" = CM.cor.p,
                 "CA spearman" = CA.cor.s,
                 "CM spearman" = CM.cor.s)
rownames(cor) = c("CN R0 = -0.1", "CN R0 = 2.5", "CN R0 = 7.5", "CN R0 = 12.5", "CN R0 = 17.5", "CN R0 = 22.5", "CN R0 = 27.5", "CN R0 = 32.5", "CN R0 = 37.5", "CN R0 = 42.5", "CN R0 = 47.5", "CN R0 = 52.5", "WCN")
knitr::kable(cor, digits = 2, caption = "Correlation structure (<z.RSD>) - sequence (CN/WCN)")
```